query FlagEntityActivityDetail($id: Int!) {
  activity(id: $id) {
    ...FlagEntityActivityDetail
  }
}

fragment FlagEntityActivityDetail on FlagEntityActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
  flag {
    id
    link
    name
  }
}
