query RevisionsBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $fieldName: String
  $originatingUserName: String
  $excludeRevisionsFromUserId: Int
  $organizationName: String
  $subjectType: ActivitySubjectInput
  $ids: [Int!]
  $status: RevisionStatus
  $sortBy: DateSort
) {
  revisionSets(
    first: $first
    last: $last
    before: $before
    after: $after
    status: $status
    fieldName: $fieldName
    originatingUserName: $originatingUserName
    excludeRevisionsFromUserId: $excludeRevisionsFromUserId
    organizationName: $organizationName
    subjectType: $subjectType
    ids: $ids
    sortBy: $sortBy
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...RevisionSetBrowseFields
      }
    }
  }
}

fragment RevisionSetBrowseFields on RevisionSet {
  id
  name
  revisions {
    id
    name
    status
    currentValue
    suggestedValue
    fieldName
    fieldDisplayName
    link
    subject {
      ... on ExonCoordinate {
        coordinateType
      }
    }
  }
  creationActivity {
    subject {
      id
      name
      link
      ... on Variant {
        feature {
          id
          name
          link
        }
      }
      ... on GeneVariant {
        feature {
          id
          name
          link
        }
      }
      ... on FactorVariant {
        feature {
          id
          name
          link
        }
      }
      ... on FusionVariant {
        feature {
          id
          name
          link
        }
      }
    }
    createdAt
    user {
      id
      displayName
      role
    }
    parsedNote {
      ...parsedCommentFragment
    }
    organization {
      id
      name
    }
  }
}