query LinkableGene($geneId: Int!) {
  gene(id: $geneId) {
    id
    name
    link
  }
}

query LinkableVariant($variantId: Int!) {
  variant(id: $variantId) {
    id
    name
    link
  }
}

query LinkableDrug($drugId: Int!) {
  drug(id: $drugId) {
    id
    name
    link
  }
}
