query DeprecateComplexMolecularProfileActivityDetail($id: Int!) {
  activity(id: $id) {
    ...DeprecateComplexMolecularProfileActivityDetail
  }
}

fragment DeprecateComplexMolecularProfileActivityDetail on DeprecateComplexMolecularProfileActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
