query RejectRevisionsActivityDetail($id: Int!) {
  activity(id: $id) {
    ...RejectRevisionsActivityDetail
  }
}

fragment RejectRevisionsActivityDetail on RejectRevisionsActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    ...RevisionActivityDetail
  }

  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
