query RevokeApprovalActivityDetail($id: Int!) {
  activity(id: $id) {
    ...RevokeApprovalActivityDetail
  }
}

fragment RevokeApprovalActivityDetail on RevokeApprovalActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
}
