query SuggestRevisionSetActivityDetail($id: Int!) {
  activity(id: $id) {
    ...SuggestRevisionSetActivityDetail
  }
}

fragment SuggestRevisionSetActivityDetail on SuggestRevisionSetActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    ...RevisionActivityDetail
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}