query VariantSelectTypeahead($name: String!, $geneId: Int) {
  variants(name: $name, geneId: $geneId, first: 50) {
    nodes {
      ... VariantSelectTypeaheadFields
    }
  }
}

fragment VariantSelectTypeaheadFields on Variant {
  id
  name
  link
  variantAliases
  singleVariantMolecularProfileId
  singleVariantMolecularProfile {
    id
    name
    link
  }
}

query VariantSelectLinkableVariant($variantId: Int!) {
  variant(id: $variantId) {
    id
    name
    link
  }
}
