query VariantSelect2($name: String!, $geneId: Int) {
  variants(name: $name, geneId: $geneId, first: 50) {
    nodes {
      ... VariantSelect2Fields
    }
  }
}

fragment VariantSelect2Fields on Variant {
  id
  name
  link
  variantAliases
  singleVariantMolecularProfileId
  singleVariantMolecularProfile {
    id
    name
    link
  }
}

query VariantSelect2LinkableVariant($variantId: Int!) {
  variant(id: $variantId) {
    id
    name
    link
  }
}
