mutation QuickAddDrug($name: String!, $ncitId: String) {
  addDrug(input: { name: $name, ncitId: $ncitId }) {
    ...QuickAddDrugFields
  }
}

fragment QuickAddDrugFields on AddDrugPayload {
  new
  drug {
    ...DrugSelectTypeaheadFields
  }
}
