fragment AcceptRevisionsActivityDetail on AcceptRevisionsActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    ...RevisionActivityDetail
  }
  supersededRevisions {
    id
    link
    name
    creationActivity {
      user {
        displayName
        id
        role
      }
    }
    fieldName
    createdAt
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
