query ModerateEvidenceItemActivityDetail($id: Int!) {
  activity(id: $id) {
    ...ModerateEvidenceItemActivityDetail
  }
}

fragment ModerateEvidenceItemActivityDetail on ModerateEvidenceItemActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
}
