query DrugSelectTypeahead($name: String!) {
  drugTypeahead(queryTerm: $name) {
    ...DrugSelectTypeaheadFields
  }
}

fragment DrugSelectTypeaheadFields on Drug {
  id
  name
  link
  ncitId
  drugAliases
}
