query DrugSelectTypeahead($name: String!) {
  drugTypeahead(queryTerm: $name) {
    ...DrugSelectTypeaheadFields
  }
}

query DrugSelectTag($id: Int!) {
  drug(id: $id) {
    ...DrugSelectTypeaheadFields
  }
}

fragment DrugSelectTypeaheadFields on Drug {
  id
  name
  link
  ncitId
  drugAliases
}
