query ResolveFlagActivityDetail($id: Int!) {
  activity(id: $id) {
    ...ResolveFlagActivityDetail
  }
}

fragment ResolveFlagActivityDetail on ResolveFlagActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
}
